# Generated by Django 3.2.16 on 2026-09-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voetbalspelers',
            options={'verbose_name': 'Voetbalspeler', 'verbose_name_plural': 'Voetbalspelers'},
        ),
    ]
